# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180506_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
